// This file is auto-generated by vite-plugin-route-builder
// Do not edit manually
/* eslint-disable */
// @ts-nocheck

import type { RouteObject } from "react-router"

// Lazy imports for page components
const lazy0 = () => import("./pages/(main)/layout")
const lazy1 = () => import("./pages/(main)/index")
const lazy2 = () => import("./pages/(main)/(layer)/timeline/[timelineId]/[feedId]/layout")
const lazy3 = () => import("./pages/(main)/(layer)/timeline/[timelineId]/[feedId]/[entryId]/index")
const lazy4 = () => import("./pages/(main)/(layer)/timeline/[timelineId]/[feedId]/index")
const lazy5 = () => import("./pages/(main)/(layer)/(subview)/layout")
const lazy6 = () => import("./pages/(main)/(layer)/(subview)/action/index")
const lazy7 = () => import("./pages/(main)/(layer)/(subview)/discover/category/[category]")
const lazy8 = () => import("./pages/(main)/(layer)/(subview)/discover/index")
const lazy9 = () => import("./pages/(main)/(layer)/(subview)/power/index")
const lazy10 = () => import("./pages/(main)/(layer)/(subview)/rsshub/index")
const lazy11 = () => import("./pages/settings/layout")
const lazy12 = () => import("./pages/settings/index")
const lazy13 = () => import("./pages/settings/(settings)/about")
const lazy14 = () => import("./pages/settings/(settings)/appearance")
const lazy15 = () => import("./pages/settings/(settings)/data-control")
const lazy16 = () => import("./pages/settings/(settings)/feeds")
const lazy17 = () => import("./pages/settings/(settings)/general")
const lazy18 = () => import("./pages/settings/(settings)/integration")
const lazy19 = () => import("./pages/settings/(settings)/invitations")
const lazy20 = () => import("./pages/settings/(settings)/list")
const lazy21 = () => import("./pages/settings/(settings)/notifications")
const lazy22 = () => import("./pages/settings/(settings)/profile")
const lazy23 = () => import("./pages/settings/(settings)/shortcuts")

// Generated route configuration
export const routes: RouteObject[] = [
  {
    "path": "",
    "lazy": lazy0,
    "children": [
      {
        "path": "",
        "lazy": lazy1
      },
      {
        "path": "",
        "children": [
          {
            "path": "timeline",
            "children": [
              {
                "path": ":timelineId",
                "children": [
                  {
                    "path": ":feedId",
                    "children": [
                      {
                        "path": "",
                        "lazy": lazy2,
                        "children": [
                          {
                            "path": ":entryId",
                            "children": [
                              {
                                "path": "",
                                "lazy": lazy3
                              }
                            ]
                          },
                          {
                            "path": "",
                            "lazy": lazy4
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "path": "",
            "lazy": lazy5,
            "children": [
              {
                "path": "action",
                "children": [
                  {
                    "path": "",
                    "lazy": lazy6
                  }
                ]
              },
              {
                "path": "discover",
                "children": [
                  {
                    "path": "category",
                    "children": [
                      {
                        "path": ":category",
                        "lazy": lazy7
                      }
                    ]
                  },
                  {
                    "path": "",
                    "lazy": lazy8
                  }
                ]
              },
              {
                "path": "power",
                "children": [
                  {
                    "path": "",
                    "lazy": lazy9
                  }
                ]
              },
              {
                "path": "rsshub",
                "children": [
                  {
                    "path": "",
                    "lazy": lazy10
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "path": "settings",
    "children": [
      {
        "path": "",
        "lazy": lazy11,
        "children": [
          {
            "path": "",
            "lazy": lazy12
          },
          {
            "path": "",
            "children": [
              {
                "path": "about",
                "lazy": lazy13
              },
              {
                "path": "appearance",
                "lazy": lazy14
              },
              {
                "path": "data-control",
                "lazy": lazy15
              },
              {
                "path": "feeds",
                "lazy": lazy16
              },
              {
                "path": "general",
                "lazy": lazy17
              },
              {
                "path": "integration",
                "lazy": lazy18
              },
              {
                "path": "invitations",
                "lazy": lazy19
              },
              {
                "path": "list",
                "lazy": lazy20
              },
              {
                "path": "notifications",
                "lazy": lazy21
              },
              {
                "path": "profile",
                "lazy": lazy22
              },
              {
                "path": "shortcuts",
                "lazy": lazy23
              }
            ]
          }
        ]
      }
    ]
  }
]

export default routes
