version: "3.8"

services:
  postgres:
    image: postgres:18
    container_name: suhui-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - suhui_pgdata:/var/lib/postgresql/data

volumes:
  suhui_pgdata:
