// This file is auto-generated by vite-plugin-route-builder
// Do not edit manually
 
// @ts-nocheck

import type { RouteObject } from "react-router"

// Lazy imports for page components
const lazy0 = () => import("./pages/(main)/layout")
const lazy1 = () => import("./pages/(main)/share/layout")
const lazy2 = () => import("./pages/(main)/share/feeds/[id]/index")
const lazy3 = () => import("./pages/(main)/share/lists/[id]/index")
const lazy4 = () => import("./pages/(main)/share/users/[id]/index")
const lazy5 = () => import("./pages/(main)/index")
const lazy6 = () => import("./pages/(login)/layout")
const lazy7 = () => import("./pages/(login)/forget-password")
const lazy8 = () => import("./pages/(login)/login/index")
const lazy9 = () => import("./pages/(login)/register")
const lazy10 = () => import("./pages/(login)/reset-password")

// Generated route configuration
export const routes: RouteObject[] = [
  {
    "path": "",
    "lazy": lazy0,
    "children": [
      {
        "path": "share",
        "children": [
          {
            "path": "",
            "lazy": lazy1,
            "children": [
              {
                "path": "feeds",
                "children": [
                  {
                    "path": ":id",
                    "children": [
                      {
                        "path": "",
                        "lazy": lazy2
                      }
                    ]
                  }
                ]
              },
              {
                "path": "lists",
                "children": [
                  {
                    "path": ":id",
                    "children": [
                      {
                        "path": "",
                        "lazy": lazy3
                      }
                    ]
                  }
                ]
              },
              {
                "path": "users",
                "children": [
                  {
                    "path": ":id",
                    "children": [
                      {
                        "path": "",
                        "lazy": lazy4
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "path": "",
        "lazy": lazy5
      }
    ]
  },
  {
    "path": "",
    "lazy": lazy6,
    "children": [
      {
        "path": "forget-password",
        "lazy": lazy7
      },
      {
        "path": "login",
        "children": [
          {
            "path": "",
            "lazy": lazy8
          }
        ]
      },
      {
        "path": "register",
        "lazy": lazy9
      },
      {
        "path": "reset-password",
        "lazy": lazy10
      }
    ]
  }
]

export default routes
